saasquatch/schema

src/json/UserMetric.schema.json

Fixed typo

---

package-lock.json
package.json
src/json/ProgramTemplate.schema.json
src/json/ProgramTransaction.schema.json
src/json/RewardApiInput.schema.json

Needed to update schema version to use with react schema form.

Ji2544 - Manual Event Schema Updates

---

.github/workflows/nodejs.yml
cloudbuild.yaml

Added Github action to automatically tests schema

Github action for automatic testing

---

package-lock.json
package.json
src/json/PurchaseEventFields.schema.json

- Jira issue number: DEV-2735
- Process.st launch checklist: https://app.process.st/checklists/Keen-jwks-update-mqyvcE3ZP6-3W2rwPMZN7g

Purchase subtotal

---

examples/jobs/user/UserWithLinksAndCodes.json
examples/webhooks/ReferralConvertedClassic.json
examples/webhooks/ReferralConvertedClassicDisabled.json
examples/webhooks/ReferralStartedClassic.json
examples/webhooks/ReferralStartedClassicDisabled.json
examples/webhooks/UserCreatedClassicDisabled.json
package-lock.json
package.json
src/json/ProgramShareLinks.schema.json
src/json/ReferralCodes.schema.json
src/json/jobs/UserImportLine.schema.json
src/json/webhooks/ReferralClassic.schema.json
src/json/webhooks/ReferralClassicDisabled.schema.json
src/json/webhooks/UserCreatedClassicDisabled.schema.json
tests/UserImportLine.test.ts

Updating webhook schema and examples with the new changes from Vanity Links and Codes
- Jira issue number: ji2783
- Process.st launch checklist: https://app.process.st/checklists/Vanity-Links-and-Codes-m2vL63FIM9e3QB_sN5JIAQ/tasks/onlBImyM_Q-rfZjJGw9HwA

Updating Webhook and User Import Schema for links and codes

---

src/json/ProgramMessages.schema.json

remove linkedInShareImageURL from required

---

package-lock.json
package.json
src/yaml/saasquatch-api.yaml

Updates the swagger spec to improve filtering in the new documentation site. 
None

LV: Adds Tags for docs personalization

---

package-lock.json
package.json
src/yaml/saasquatch-api.yaml

Adding deprecated tags and boolean flag, plus minor description update for lookup referral code
Uncommenting exports tag to fix linking bug
- Jira issue number: N/A
- Process.st launch checklist: N/A

Swagger API updates

---

package-lock.json
package.json
src/json/TenantJob.schema.ts
src/json/jobs/JobParams.ts
src/yaml/saasquatch-api.yaml

> Add user stats fields param to job schema and update schema to include other missing parameters
- Jira issue number: DEV-2986
- Process.st launch checklist: https://app.process.st/checklists/DEV-2986-User-stats-update-qZoJs_nwOk6MDIGgg2NPRg

DEV-2986: Add user stats to user details

---

package-lock.json
package.json
src/yaml/saasquatch-api.yaml

> Minor formatting update
- Jira issue number: DEV-2986
- Process.st launch checklist: https://app.process.st/checklists/DEV-2986-User-stats-update-qZoJs_nwOk6MDIGgg2NPRg

DEV-2986: Minor formatting

---

package-lock.json
package.json
src/yaml/saasquatch-api.yaml

Updating Swagger schema to reflect changes to our API endpoints for W-9, and roll in a missing Classic Only tag.
When approved and merged we can also close https://github.com/saasquatch/schema/pull/47
- Jira issue number: DEV-3008
- Process.st launch checklist: https://app.process.st/checklists/DEV-3008-W-9-documentation-updates-op87iSCjGxSBJ2sTiDhKZg

DEV-3008: W-9 Swagger Updates

---

src/json/UserMetric.schema.json

add last seen to user metrics

---

src/yaml/saasquatch-api.yaml

Adding country code to Open Endpoint Methods
Input for:
Upsert User
Create User
Output for:
Upsert User
Create User
Lookup User

Adding country code to Open Endpoint Methods

---

examples/jobs/userEvent/invalid0.json
examples/jobs/userEvent/invalid1.json
examples/jobs/userEvent/invalid2.json
examples/jobs/userEvent/invalid3.json
examples/jobs/userEvent/invalid4.json
examples/jobs/userEvent/invalid5.json
examples/jobs/userEvent/valid0.json
examples/jobs/userEvent/valid1.json
examples/jobs/userEvent/valid2.json
helpers/Validator.ts
package-lock.json
package.json
src/json/jobs/UserEventImportLine.schema.json
tests/Form.test.ts
tests/UserEventImportLine.test.ts

- Jira issue number: DEV-3048
- Process.st launch checklist: https://app.process.st/checklists/DEV-3048-Events-import-q975ki89wmhFG3A6t8BJ-Q

DEV-3048: Event import

---

package-lock.json
package.json
src/json/HostedPortalConfig.schema.json
src/json/ManagedIdentityConfig.schema.json

Add JSON schema for the Hosted Portal Config
- Jira issue number: DEV-3245
- Process.st launch checklist: [here](https://app.process.st/runs/DEV-3245-Managed-Identity-Update-P1-pSOkYd7fnJIXgPkZ2KpO5g/tasks/ipJPSwLUytFe3xMt6P5PYw)

[DEV-3245] Hosted Portal Config Schema

---

CHANGELOG.md
package-lock.json
package.json
src/json/ProgramTransaction.schema.json

Add schema for the EXCHANG_REWARD program mutation.
- Jira issue number: [DEV-3273](https://saasquatch.atlassian.net/browse/DEV-3273)
- Process.st launch checklist: https://app.process.st/runs/DEV-3273-Program-reward-exchange-mutation-qyT3RoZENkqlWbsrajpDwQ

[DEV-3273] EXCHANGE_REWARD mutation

---

CHANGELOG.md

Fix schema changelog date for 1.21

---

CHANGELOG.md
package-lock.json
package.json
src/json/TenantJob.schema.ts

Add tenant job schema for user events report.
- Jira issue number: DEV-3280
- Process.st launch checklist: https://app.process.st/runs/DEV-3280-User-Event-Retention-vPJU1SM7hBs_bgh_CvpGow/tasks/ipJPSwLUytFe3xMt6P5PYw

[DEV-3280]: Tenant job schema for user events report

---

CHANGELOG.md
package-lock.json
package.json
src/json/IntegrationConfig.schema.json
src/json/webhooks/UserCreatedClassicDisabled.schema.json

PR for any HubSpot schema updates
* Fixed typos in GA `user.created` webhook schema
* Add integration managed user events
- Jira issue number: DEV-3402

[DEV-3402] HubSpot Updates

---

CHANGELOG.md
package-lock.json
package.json
src/json/HtmlEmail.schema.json

Add bcc to html email template
- Jira issue number: DEV-3417
- Process.st launch checklist:  https://app.process.st/runs/DEV-3417-BCC-backend-kBC4ZX9w_mEWStevoUpDvw

[DEV-3417] BCC backend

---

CHANGELOG.md
package-lock.json
package.json
src/yaml/saasquatch-api.yaml

remove Create Cookie User from swagger schema
- Jira issue number: DEV-3312
- Process.st launch checklist: https://app.process.st/runs/DEV-3312-Kill-Recurly-and-cookie-users-mBMFjEgsHNFf9xLAlaBOeQ/tasks/iMor9TF4aDCRtDh7tqtEHA

[DEV-3312]: remove Create Cookie User from swagger schema

---

CHANGELOG.md
package-lock.json
package.json
src/json/ManagedIdentityConfig.schema.json

Add `HASHED_EMAIL` to managed identity config
- Jra issue number: https://impact.atlassian.net/browse/SQDEV-3462
- Process.st launch checklist: [Checklist](https://app.process.st/runs/Milestone-1-Schema-k5WqSuuGytz5I6VsttJEkg/tasks/ipJPSwLUytFe3xMt6P5PYw)

[SQDEV-3462] Milestone 1

---

CHANGELOG.md
package-lock.json
package.json
src/json/jobs/UserEventImportLine.schema.json

- Jira issue number: SQDEV-3500

[SQDEV-3500] Add idempotencyKey to event import schema

---

CHANGELOG.md
package-lock.json
package.json
src/json/ProgramTransaction.schema.json

- Added the new `RETRACT_REFERRAL_CONVERSION` mutation for program transactions
- Jira issue number: SQDEV-3594
- Process.st launch checklist: https://app.process.st/runs/SQDEV-3594-Feature-Enforcement-Backend-Launch-kaMh2HzxmaT1VTipLsRM-Q/tasks/ipJPSwLUytFe3xMt6P5PYw

[SQDEV-3594] Feature enforcement backend

---

CHANGELOG.md
package-lock.json
package.json
src/json/ProgramMessages.schema.json

> Replace old Twitter copy with new X branding 

Update old twitter copy

---

CHANGELOG.md
package-lock.json
package.json
src/json/ProgramTransaction.schema.json

Add RETRACT_REFERRAL_CONVERSION to mutation enum

---

.github/workflows/nodejs.yml
CHANGELOG.md
compilers/SchemaToTypescript.ts
compilers/Version.ts
package-lock.json
package.json
src/json/microsite/MicrositeTemplate.schema.json
src/json/program/obj-referral-program/program-template.json
src/json/program/obj-referral-program/rules.schema.json
tsconfig.json

Update microsite template to allow tenantSettings.usTaxNotificationEmailKey to be included in the template
- Jira issue number: SQDEV-3569
- Process.st launch checklist: https://app.process.st/runs/SQDEV-3569-Advocate-Base-Backend-hiY7ivGkjTWquJR4midMxA/tasks/ipJPSwLUytFe3xMt6P5PYw

[SQDEV-3569] Advocate base backend
